// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package public_graph_model

import (
	cloud_account_model "brume.dev/cloud/account/model"
)

type CreateCloudAccountInput struct {
	Name          string                            `json:"name"`
	AccountID     string                            `json:"accountId"`
	CloudProvider cloud_account_model.CloudProvider `json:"cloudProvider"`
}

type CreateCloudAccountResponse struct {
	ID string `json:"id"`
}

type DeployStackInput struct {
	Name           string `json:"name"`
	TemplateID     string `json:"templateId"`
	CloudAccountID string `json:"cloudAccountId"`
}

type DeployStackResponse struct {
	ID string `json:"id"`
}

type Mutation struct {
}

type Query struct {
}
