// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package public_graph_model

type Organization struct {
	ID         string `json:"id"`
	ProviderID string `json:"providerId"`
	Name       string `json:"name"`
}

type Query struct {
}
