FROM golang:1.23-alpine as base-brume

WORKDIR /brume

RUN go work sync

FROM base-brume as agent

WORKDIR /brume/agent

# install hot reload solution
RUN go install github.com/air-verse/air@latest

CMD ["air", "-c", ".air.toml"]
