[logs]
cmd = "silent"
authentification = "silent"
account_user = "silent"
account_org = "silent"
builder = "silent"
deployment_workflow = "silent"
deployment_service = "silent"
machine_workflow = "silent"
clickhouse = "silent"
db = "silent"
fx = "info"
redis = "silent"
grpc = "silent"
http = "silent"
graphql_public = "silent"
temporal_client = "silent"
temporal_worker = "silent"
ticker = "silent"
http_middleware = "silent"
machine = "silent"
grpc_interceptor = "silent"
grpc_server = "silent"
bid_service = "silent"
job_service = "silent"
log_activity = "silent"
service = "silent"
project = "silent"
job_workflow = "silent"


[orchestrator]
unhealthy_machine_threshold = 10
unhealthy_job_threshold = 10
reschedule_jobs = false

# ticker configuration
[ticker]
rapid_ticker = 5

# all servers running on the orchestrator
[server]
host = "0.0.0.0"
orchestrator_port = 9876
graphql_port = 9877
grpc_port = 9878

# postgres configuration
[postgres]
host = "postgres"
port = 5432
db = "brume"
user = "brume"
password = "brumepass"
max_idle = 1
max_open = 1
logs = "info"

# redis configuration
[redis]
host = "redis"
port = 6379
db = 0
password = ""

# temporal configuration
[temporal]
host = "temporal"
port = 7233

# clickhouse configuration
[clickhouse]
host = "clickhouse"
port = 9000
db = "brume"
user = "brume"
password = "brumepass"
