FROM golang:1.25-alpine AS base_brume

WORKDIR /brume

RUN go work init
RUN go work sync

# install hot reload solution
RUN go install github.com/air-verse/air@latest

FROM base_brume AS brume

WORKDIR /brume/brume

CMD ["air", "-c", ".air.toml"]
