package public_graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.57

import (
	"context"
	"errors"

	user_model "brume.dev/account/user/model"
	builder_model "brume.dev/builder/model"
	generated "brume.dev/internal/router/public-gql/graph/generated/generated.go"
	public_graph_model "brume.dev/internal/router/public-gql/graph/model"
	project_model "brume.dev/project/model"
	runner_model "brume.dev/runner/model"
	service_model "brume.dev/service/model"
	source_model "brume.dev/source/model"
	"github.com/google/uuid"
)

// ID is the resolver for the id field.
func (r *builderResolver) ID(ctx context.Context, obj *builder_model.Builder) (string, error) {
	return obj.ID.String(), nil
}

// ID is the resolver for the id field.
func (r *projectResolver) ID(ctx context.Context, obj *project_model.Project) (string, error) {
	return obj.ID.String(), nil
}

// IsDirty is the resolver for the isDirty field.
func (r *projectResolver) IsDirty(ctx context.Context, obj *project_model.Project) (bool, error) {
	return r.ProjectService.IsDirty(obj)
}

// Services is the resolver for the services field.
func (r *projectResolver) Services(ctx context.Context, obj *project_model.Project) ([]*service_model.Service, error) {
	betterProject, err := r.ProjectService.GetProject(obj)
	return betterProject.Services, err
}

// Me is the resolver for the me field.
func (r *queryResolver) Me(ctx context.Context) (*user_model.User, error) {
	pid := ctx.Value("user").(string)
	user, err := r.UserService.GetUserByProviderID(pid)
	if err != nil {
		return nil, err
	}

	return user, nil
}

// GetProjectByID is the resolver for the getProjectById field.
func (r *queryResolver) GetProjectByID(ctx context.Context, id string) (*project_model.Project, error) {
	project_uuid, err := uuid.Parse(id)
	if err != nil {
		return nil, err
	}

	return r.ProjectService.GetProjectByID(project_uuid)
}

// ID is the resolver for the id field.
func (r *runnerResolver) ID(ctx context.Context, obj *runner_model.Runner) (string, error) {
	return obj.ID.String(), nil
}

// ID is the resolver for the id field.
func (r *serviceResolver) ID(ctx context.Context, obj *service_model.Service) (string, error) {
	return obj.ID.String(), nil
}

// ID is the resolver for the id field.
func (r *sourceResolver) ID(ctx context.Context, obj *source_model.Source) (string, error) {
	return obj.ID.String(), nil
}

// Type is the resolver for the type field.
func (r *sourceResolver) Type(ctx context.Context, obj *source_model.Source) (string, error) {
	return string(obj.Type), nil
}

// Data is the resolver for the data field.
func (r *sourceResolver) Data(ctx context.Context, obj *source_model.Source) (any, error) {
	if obj.Type == source_model.SourceTypeGit {
		return obj.GitData, nil
	}

	return nil, errors.New("source type not supported")
}

// ID is the resolver for the id field.
func (r *userResolver) ID(ctx context.Context, obj *user_model.User) (string, error) {
	return obj.ID.String(), nil
}

// Projects is the resolver for the projects field.
func (r *userResolver) Projects(ctx context.Context, obj *user_model.User) ([]*project_model.Project, error) {
	projects, err := r.UserService.GetUserProjects(obj)

	return projects, err
}

// Organization is the resolver for the organization field.
func (r *userResolver) Organization(ctx context.Context, obj *user_model.User) (*public_graph_model.Organization, error) {
	org, err := r.UserService.GetUserOrganization(obj)
	if err != nil {
		return nil, err
	}

	return &public_graph_model.Organization{
		ID:         org.ID.String(),
		ProviderID: org.ProviderID,
		Name:       org.Name,
	}, nil
}

// Builder returns generated.BuilderResolver implementation.
func (r *Resolver) Builder() generated.BuilderResolver { return &builderResolver{r} }

// Project returns generated.ProjectResolver implementation.
func (r *Resolver) Project() generated.ProjectResolver { return &projectResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

// Runner returns generated.RunnerResolver implementation.
func (r *Resolver) Runner() generated.RunnerResolver { return &runnerResolver{r} }

// Service returns generated.ServiceResolver implementation.
func (r *Resolver) Service() generated.ServiceResolver { return &serviceResolver{r} }

// Source returns generated.SourceResolver implementation.
func (r *Resolver) Source() generated.SourceResolver { return &sourceResolver{r} }

// User returns generated.UserResolver implementation.
func (r *Resolver) User() generated.UserResolver { return &userResolver{r} }

type builderResolver struct{ *Resolver }
type projectResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type runnerResolver struct{ *Resolver }
type serviceResolver struct{ *Resolver }
type sourceResolver struct{ *Resolver }
type userResolver struct{ *Resolver }
