package public_graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.57

import (
	"context"
	"errors"

	org_model "brume.dev/account/org/model"
	user_model "brume.dev/account/user/model"
	cloud_account_service "brume.dev/cloud/account"
	cloud_account_model "brume.dev/cloud/account/model"
	generated "brume.dev/internal/router/public-gql/graph/generated/generated.go"
	public_graph_model "brume.dev/internal/router/public-gql/graph/model"
	project_model "brume.dev/project/model"
	service_model "brume.dev/service/model"
	source_model "brume.dev/source/model"
	stack_service "brume.dev/stack"
	stack_model "brume.dev/stack/model"
)

// Stacks is the resolver for the stacks field.
func (r *cloudAccountResolver) Stacks(ctx context.Context, obj *cloud_account_model.CloudAccount) ([]*stack_model.Stack, error) {
	cloudAccount, err := r.CloudAccountService.WithStacks(ctx, obj)
	if err != nil {
		return nil, err
	}
	return cloudAccount.Stacks, nil
}

// CreateCloudAccount is the resolver for the createCloudAccount field.
func (r *mutationResolver) CreateCloudAccount(ctx context.Context, input public_graph_model.CreateCloudAccountInput) (*public_graph_model.CreateCloudAccountResponse, error) {
	data, err := r.CloudAccountService.BeginCreateCloudAccount(ctx, cloud_account_service.CreateCloudAccountInput{
		Name:          input.Name,
		AccountID:     input.AccountID,
		CloudProvider: input.CloudProvider,
	})

	if err != nil {
		return nil, err
	}

	return &public_graph_model.CreateCloudAccountResponse{
		ID: data.ID,
	}, nil
}

// DeployStack is the resolver for the deployStack field.
func (r *mutationResolver) DeployStack(ctx context.Context, input public_graph_model.DeployStackInput) (*public_graph_model.DeployStackResponse, error) {
	data, err := r.StackService.StartStackDeployment(ctx, stack_service.StartStackDeploymentInput{
		Name:           input.Name,
		TemplateID:     input.TemplateID,
		CloudAccountID: input.CloudAccountID,
	})
	if err != nil {
		return nil, err
	}

	return &public_graph_model.DeployStackResponse{
		ID: data.ID,
	}, nil
}

// CloudAccounts is the resolver for the cloudAccounts field.
func (r *organizationResolver) CloudAccounts(ctx context.Context, obj *org_model.Organization) ([]*cloud_account_model.CloudAccount, error) {
	accounts, err := r.OrganizationService.GetOrganizationCloudAccounts(obj)
	if err != nil {
		return nil, err
	}
	// convert to []*cloud_account_model.CloudAccount
	accountsList := make([]*cloud_account_model.CloudAccount, len(accounts))
	for i, account := range accounts {
		accountsList[i] = &account
	}
	return accountsList, nil
}

// IsDirty is the resolver for the isDirty field.
func (r *projectResolver) IsDirty(ctx context.Context, obj *project_model.Project) (bool, error) {
	return r.ProjectService.IsDirty(obj)
}

// Services is the resolver for the services field.
func (r *projectResolver) Services(ctx context.Context, obj *project_model.Project) ([]*service_model.Service, error) {
	betterProject, err := r.ProjectService.GetProject(obj)
	return betterProject.Services, err
}

// Me is the resolver for the me field.
func (r *queryResolver) Me(ctx context.Context) (*user_model.User, error) {
	pid := ctx.Value("user").(string)
	user, err := r.UserService.GetUserByProviderID(pid)
	if err != nil {
		return nil, err
	}

	return user, nil
}

// GetProjectByID is the resolver for the getProjectById field.
func (r *queryResolver) GetProjectByID(ctx context.Context, id string) (*project_model.Project, error) {
	return r.ProjectService.GetProjectByID(id)
}

// GetAWSCloudFormationURL is the resolver for the getAWSCloudFormationURL field.
func (r *queryResolver) GetAWSCloudFormationURL(ctx context.Context) (string, error) {
	policyURL := r.ConfigService.BrumeGeneralConfig.PolicyURL
	trustArn := r.ConfigService.BrumeGeneralConfig.BrumeTrustArn

	baseUrl := "https://eu-west-3.console.aws.amazon.com/cloudformation/home?region=eu-west-3#/stacks/quickcreate?templateURL=" + policyURL + "&stackName=BrumeInitStack&param_TrustArnParameter=" + trustArn
	return baseUrl, nil
}

// GetCloudAccountByID is the resolver for the getCloudAccountById field.
func (r *queryResolver) GetCloudAccountByID(ctx context.Context, id string) (*cloud_account_model.CloudAccount, error) {
	return r.CloudAccountService.GetCloudAccountByID(ctx, id)
}

// GetStackTemplates is the resolver for the getStackTemplates field.
func (r *queryResolver) GetStackTemplates(ctx context.Context) ([]*stack_model.StackTemplate, error) {
	return r.StackService.GetAllStackTemplates(ctx)
}

// GetStacks is the resolver for the getStacks field.
func (r *queryResolver) GetStacks(ctx context.Context) ([]*stack_model.Stack, error) {
	return r.StackService.GetAllStacks(ctx)
}

// GetStack is the resolver for the getStack field.
func (r *queryResolver) GetStack(ctx context.Context, id string) (*stack_model.Stack, error) {
	return r.StackService.GetStackByID(ctx, id)
}

// Type is the resolver for the type field.
func (r *sourceResolver) Type(ctx context.Context, obj *source_model.Source) (string, error) {
	return string(obj.Type), nil
}

// Data is the resolver for the data field.
func (r *sourceResolver) Data(ctx context.Context, obj *source_model.Source) (any, error) {
	if obj.Type == source_model.SourceTypeGit {
		return obj.GitData, nil
	}

	return nil, errors.New("source type not supported")
}

// Projects is the resolver for the projects field.
func (r *userResolver) Projects(ctx context.Context, obj *user_model.User) ([]*project_model.Project, error) {
	projects, err := r.UserService.GetUserProjects(obj)

	return projects, err
}

// Organization is the resolver for the organization field.
func (r *userResolver) Organization(ctx context.Context, obj *user_model.User) (*org_model.Organization, error) {
	org, err := r.UserService.GetUserOrganization(obj)
	if err != nil {
		return nil, err
	}

	return &org_model.Organization{
		ID:   org.ID,
		Name: org.Name,
	}, nil
}

// CloudAccount returns generated.CloudAccountResolver implementation.
func (r *Resolver) CloudAccount() generated.CloudAccountResolver { return &cloudAccountResolver{r} }

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Organization returns generated.OrganizationResolver implementation.
func (r *Resolver) Organization() generated.OrganizationResolver { return &organizationResolver{r} }

// Project returns generated.ProjectResolver implementation.
func (r *Resolver) Project() generated.ProjectResolver { return &projectResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

// Source returns generated.SourceResolver implementation.
func (r *Resolver) Source() generated.SourceResolver { return &sourceResolver{r} }

// User returns generated.UserResolver implementation.
func (r *Resolver) User() generated.UserResolver { return &userResolver{r} }

type cloudAccountResolver struct{ *Resolver }
type mutationResolver struct{ *Resolver }
type organizationResolver struct{ *Resolver }
type projectResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type sourceResolver struct{ *Resolver }
type userResolver struct{ *Resolver }

// !!! WARNING !!!
// The code below was going to be deleted when updating resolvers. It has been copied here so you have
// one last chance to move it out of harms way if you want. There are two reasons this happens:
//  - When renaming or deleting a resolver the old code will be put in here. You can safely delete
//    it when you're done.
//  - You have helper methods in this file. Move them out to keep these resolver files clean.
/*
	func (r *queryResolver) GetStackByID(ctx context.Context, id string) (*stack_model.Stack, error) {
	return r.StackService.GetStackByID(ctx, id)
}
*/
