# NOTE: This docker image needs to be built with `--context` set to the parent directory of this file
FROM node:22.4-alpine3.19 AS base

    WORKDIR /app

    COPY package.json yarn.lock ./

    RUN yarn install --frozen-lockfile

FROM base AS dev

    COPY . .

    CMD ["yarn", "dev", "--logLevel", "info", "--host"]
