# NOTE: This docker image needs to be built with `--context` set to the parent directory of this file
FROM node:22.4-alpine3.19 AS base

WORKDIR /app

RUN npm install -g pnpm@10

COPY package.json pnpm-lock.yaml ./

RUN pnpm install --frozen-lockfile

FROM base AS dev

COPY . .

CMD ["yarn", "dev", "--logLevel", "info", "--host"]
