machine_id = "b36d84e9-bec2-4ba1-8b51-536884f06bc7"

[orchestrator]
url = "http://orchestrator:9876"
rapid_ticker = 2
slow_ticker = 5
retry_max = 3

[logs]
collector = "silent"
runner_docker = "silent"
health = "silent"
job = "silent"
runner = "silent"
ticker = "silent"
fx = "silent"
intercom = "silent"
docker = "silent"
cmd = "silent"
