FROM golang:1.23-alpine

WORKDIR /agent

# install hot reload solution
RUN go install github.com/air-verse/air@latest

COPY go.mod go.sum ./
RUN go mod download

EXPOSE 9878

CMD ["air", "-c", ".air.toml"]
