FROM golang:1.23-alpine

WORKDIR /brume

# install hot reload solution
RUN go install github.com/air-verse/air@latest

COPY go.mod go.sum ./
RUN go mod download

EXPOSE 9878

COPY . .

CMD ["air", "-c", ".air.toml"]
